[build]
command = "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8080"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[routes]
pattern = "/"
script = "app.py"
